# Generated by Django 3.2.9 on 2021-12-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
